services:
  postgres:
    image: "postgres:16.0"
    restart: always
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "25555:5432"
  my-mongodb:
    image: mongo:6-jammy
    container_name: my-mongodb
    ports:
      - 27018:27017


