--liquibase formatted sql

--changeset metlushkoaa:1
CREATE TABLE IF NOT EXISTS "users"
(
    id       bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled  boolean

);

create table authorities
(
    username  varchar,
    authority varchar

);

--changeset metlushkoaa:2

-- INSERT INTO "persons" (username, password, role)
-- VALUES ('name1', '123', 'admin');
--
-- INSERT INTO "persons" (username, password, role)
-- VALUES ('name2', '123', 'admin');
--
-- INSERT INTO "persons" (username, password, role)
-- VALUES ('name3', '123', 'user');
--
-- INSERT INTO "persons" (username, password, role)
-- VALUES ('name4', '123', 'user');



